### ISSUE TITLE
Unexpected behavior on synchronous call

### ISSUE THREAD

**Issue by WrinkleJ** [Guseyn/cutie#131]
Hi, Guseyn!
I tried your framework and got unexpected behavior with synchronous call.

For example, i want to create two classes with sync and async behavior, for read and write files.

**WrittenFile**
```js
const AsyncObject = require('@cuties/cutie').AsyncObject
const fs = require('fs')

class WrittenFile extends AsyncObject {
    constructor(path, content) {
        super(path, content);
    }

    asyncCall() {
        return (path, content, callback) => {
            this.path = path;
            fs.writeFile(path, content, callback)
            console.log("asyncCall writtenFile");
        }
    }

    syncCall() {
        return (path, content, callback) => {
            this.path = path;
            fs.writeFileSync(path, content, callback)
            console.log("syncCall writtenFile");
        }
    }

    onResult() {
        console.log("writtenFile has done!");
    }
}

module.exports = WrittenFile;
```

**ReadDataByPath**
```js
const AsyncObject = require('@cuties/cutie').AsyncObject
const fs = require('fs')

class ReadDataByPath extends AsyncObject {
  constructor (path, encoding) {
    super(path, encoding);
  }
  
  asyncCall () {
    return fs.readFile
  }

  syncCall() {
      return fs.readFileSync
  }
}

module.exports = ReadDataByPath
```

And if i want to run as sync operation, i do

```js
new WrittenFile(
    'package2.json',
    new ReadDataByPath('package.json', 'utf-8')
).syncCall();
```
but nothing happens.

How can i create one class with two behaviors (async and sync)?

**Comment by Guseyn** [comment]
@WrinkleJ Hi, thanks for posting the issue and sorry for late response
You cannot use `asyncCall()` and `syncCall()` together, I mean you can, but only `asyncCall()` will be invoked. You need to create separate classes for sync and async versions of calls, look at http://github.com/guseyn/cutie-fs. You'll find examples there.

**Comment by Guseyn** [comment]
@WrinkleJ And nothing happens because you need to use `call()` method instead of `syncCall()`
```
new WrittenFile(
    'package2.json',
    new ReadDataByPath('package.json', 'utf-8')
).call()
```

**Comment by Guseyn** [comment]
@WrinkleJ I am closing the ticket if you don't mind. I think I answered it.

**Comment by WrinkleJ** [comment]
Hi, Guseyn! I don't mind. Thank u for answer :)
